### ISSUE TITLE
Does not work with luckperms 5

### ISSUE THREAD

**Issue by wozeparrot** [strifel/VBans#1]
Luckperms 5 changed the api and this plugin no longer supports it.

**Comment by strifel** [comment]
Will have a look into that

**Comment by wozeparrot** [comment]
I have found a workaround using the luckperms 4 extension. https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#installing-the-extension

**Comment by strifel** [comment]
(Finally) closed by #4 

This drops LuckPerms4 support
