### ISSUE TITLE
Banning players who are offline or never even played on the server

### ISSUE THREAD

**Issue by gold-ly** [strifel/VBans#14]
Hey,
I noticed you can't ban players if they aren't online. I guess that is due to the lack of a function in Velocity to get the UUID of an offline player.
However, I think this is important, e.g. if a player insults someone and then leaves he can't get banned until he joins again.

The solution for this would be to use the official Mojang API to get the UUID of an offline player. It is documented [here](https://wiki.vg/Mojang_API#Usernames_to_UUID). 

I don't know if you are still maintaining this, but if you are, please consider adding this feature.

**Comment by strifel** [comment]
Do you have luckperms installed?

**Comment by gold-ly** [comment]
It works now, thanks for your reply. I don't know why, because I had LuckPerms installed all the time and I didn't got any errors in the console.
But still, players that never played on the server can't get banned.

**Comment by strifel** [comment]
Thanks for your feedback!
