### ISSUE TITLE
In game commands not working

### ISSUE THREAD

**Issue by fools12** [strifel/VBans#2]
I have two servers running on Velocity. I have installed VBans on the proxy (Velocity)  and I cannot use any in game commands on the two other servers. (Other two servers are sponge based)

When I use the commands in the console of the velocity server It works fine and bans players like it should. 

Is there another plugin I have to install on the other two non velocity servers?

**Comment by strifel** [comment]
It should work like that. Maybe you haven't set the permissions for the players properly?

**Comment by fools12** [comment]
The permissions are all set correctly using the permissions from the VBans Velocity page.
Its like the backend servers don't know the commands exist.

**Comment by strifel** [comment]
Do commands from other plugins work?

**Comment by fools12** [comment]
Yes they do.

I just updated my Velocity version from 1.0.5 to 1.0.6.
I don't know if i am doing something wrong but its not working on either version.

**Comment by fools12** [comment]
Any Updates?

**Comment by strifel** [comment]
Hi. Sorry for answering so late. (And thank you for reminding me)

Can you please try giving an online player the permission `VBans.bannedBroadcast` and banning a different player from console? This would show if there is a problem somewehere with the permissions or the commands itself.

There arent't any issues showing up in console?

Check that you have set changeToGCommands to false (should be default) if you want to use /ban not /gban.

Also if you could test if `/vkick` and `/vban` won't work either.

Also please check if [the older version](https://github.com/strifel/VBans/releases/download/1.0-SNAPSHOT/VBans.jar) works.

I have not worked with Velocity or this codebase in close to half a year. 
Please let me hear back if any tries work.

**Comment by strifel** [comment]
Just tested on the newest 1.1 beta and it works for me

**Comment by fools12** [comment]
Just updated. I got it to work thanks!
