### ISSUE TITLE
JDBC Download Error

### ISSUE THREAD

**Issue by Thesam1798** [strifel/VBans#3]
The JDBC url is down...
This causes a fatal error

Error Line :
> java.io.FileNotFoundException: https://cdn.mysql.com//Downloads/Connector-J/mysql-connector-java-8.0.18.zip

Download Line : https://github.com/strifel/VBans/blob/f43155d22aa3c6445113f1d6a7482991a8f3ff26/src/main/java/de/strifel/vbans/JDBC.java#L25

Replace with :
https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.20.zip

Log : [https://hastebin.com/raw/ixuruzutak](https://hastebin.com/raw/ixuruzutak)

**Comment by strifel** [comment]
Closed by #4
