### ISSUE TITLE
Plugin class JDBC build error

### ISSUE THREAD

**Issue by InseiderHD** [strifel/VBans#5]
Error Line: try (FileSystem zipFileSystem = FileSystems.newFileSystem(**zip, null**)) {

https://user-images.githubusercontent.com/76958201/119857303-bbbde400-bf13-11eb-9ebd-d7d7d6d432ef.png

Code + Error:

https://user-images.githubusercontent.com/76958201/119856727-3df9d880-bf13-11eb-9220-f043ef921b82.png

**Comment by strifel** [comment]
Hi,
thanks for the report.

Please add which Java version you are using

**Comment by InseiderHD** [comment]
I use Java 16

**Comment by InseiderHD** [comment]
Oh in Java 1.8 it works

**Comment by strifel** [comment]
@InseiderHD please try the newest master again.
I fixed that issue.
