### ISSUE TITLE
Plugin does not run without LuckPerms

### ISSUE THREAD

**Issue by KastenKlicker** [strifel/VBans#6]
The plugin doesn't load, because of an error caused by LuckPerms.
I downloaded the newest release and it's the only plugin on my velocity 1.1.5 proxy.
[latest.log](https://github.com/strifel/VBans/files/6568895/latest.log)

**Comment by strifel** [comment]
Hi,
the error does suggest that the plugin does not run without LuckPerms installed.
You do need a permissions plugin installed anyway.

But I would have guessed that it works without LuckPerms installed. I will test that.

**Comment by KastenKlicker** [comment]
Thank you for the fast reply.

**Comment by strifel** [comment]
I attached a zip (can not directly attach jar) that contains a jar file that should have this issue fixed 
[vbans-no-luckperms-required.jar.zip](https://github.com/strifel/VBans/files/6569096/vbans-no-luckperms-required.jar.zip)
