### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oy2** [strifel/VBans#9]
Hey,

Would it be possible for you to add an open source license to this project (MIT/Unlicense/GPL/WTFPL/etc), or clarify if this source is all rights reserved?

Thanks!

**Comment by strifel** [comment]
Hi,
thanks for the issue.
I did not know I forgot to use a license.

As some code is not from me I think I need to get permissions to use a license for it.

I will do that

**Comment by strifel** [comment]
Im sorry it took so long.
Just saw this issue was open and decided to finally do it.
